### ISSUE TITLE
casual2

### ISSUE THREAD

**Issue by yu-chenxi** [lyy7595/BOOK#15]
```html
<html>
  <head>
    <title>this is a simple html doc</title>
  </head>
  <body>
    <p>
      HOLLY SHIT!
    </p>
  </body>
</html>
````

#### 不第后赋菊
> 待到秋来九月八, 我花开后百花杀
> 冲天香阵透长安, 满城尽带黄金甲

```yaml
animal:
 - cat
 - dog
 - pig
word:
 tension:张力
 rivet:铆接
```

```toml
[person]
age = 18
name = 'ycx'
person.addr = 'zhuji'
```
